#
# We want to deploy to all regions to handle requests at the
# Edge. To do so, we rely on AWS StackSets. For an overview of
# permissions and other work we did to make this work, see:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-prereqs.html
# 
# We use self-managed permissions rather than service-managed
# permissions because we want to deploy resources into the same
# AWS account as is administrating the stack, and:
#
#   "StackSets doesn't deploy stack instances to the organization's
#   management account, even if the management account is in your
#   organization or in an OU in your organization."
#
#   From: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-getting-started-create.html
#
# To manage StackSets, the calling user/role will need permission
# assume the StackSets administrator role.
#
# To create the stack set:
#
#   aws cloudformation create-stack-set \
#     --profile admin-role-here \
#     --stack-set-name dev-search-edge-request \
#     --template-body file://search-sns-cloudformation.yml \
#     --description "SNS topic for search requests at the edge"
#
# To create instances:
#
#   aws cloudformation create-stack-instances \
#     --profile admin-role-here \
#     --stack-set-name dev-search-edge-request \
#     --accounts '["167811431063"]' \
#     --regions '["us-west-2", "us-west-1"]'
#
# Modify accounts and regions as needed. For convenince, these
# are all regions we're using as of June 2022:
#   ["eu-north-1", "ap-south-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-3", "ap-northeast-2", "ap-northeast-1", "sa-east-1", "ca-central-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
#
# To get a list of regions we use:
#   aws ec2 describe-regions
#
# To update stack sets, see:
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-update.html
#
# Use `./scripts/set-search-sns-stack-policy.mjs` to manage stack policies
# before and after modifying stacks.
#
Resources:
  # Topic ARNs will be identical but for their region:
  # arn:aws:sns:us-west-1:167811431063:SearchRequest
  SearchRequestSNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "Search request SNS topic"
      # Change to test-SearchRequest or SearchRequest (prod), as needed
      TopicName: dev-SearchRequest
      FifoTopic: false
